"""Regression guard for the git-upload path clean-up.

Verifies that mobility_index / mating_index / reid_benchmark resolve every default
data/model path to something that actually exists inside this repo (no leftover
QNAP / D:-drive / personal-machine paths), and that no such string remains anywhere
in the tracked source. Run with ``pytest`` from the repo root.

The dataset itself is hosted on Mendeley Data, not in this git repo (see the top-level
README's "Dataset availability" section) - only ``models/`` is tracked in git.
Checks that depend on the Mendeley archive being downloaded and extracted into
``datasets/`` (this includes ``datasets/additional/``) are skipped (not failed) if it
isn't there yet.
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

FORBIDDEN_PATTERNS = [
    r"QNAP",
    r"doswiadczenie_re_identyfikacja",
    r"D:[/\\]",
    r"C:[/\\]projects",
    r"C:[/\\]my_envs",
    r"/Tenebrio/",
]

# directories whose content is either regenerated pipeline output or genuinely-large
# binary datasets - not worth scanning (and may contain paths baked in at run time,
# e.g. YOLO's args.yaml, which are gitignored and irrelevant here).
EXCLUDED_DIR_NAMES = {
    ".git", ".venv", "__pycache__", ".pytest_cache",
    "outputs", "runs", "runs_check", "models",
}
TEXT_SUFFIXES = {".py", ".md", ".yaml", ".yml", ".txt", ".cfg", ".ini"}

MENDELEY_NOTE = (
    "the Mendeley Data dataset archive is not downloaded/extracted into datasets/ "
    "yet - see the top-level README's Dataset availability section"
)


def _skip_if_dataset_missing(path: Path):
    if not path.exists():
        pytest.skip(f"{path} missing: {MENDELEY_NOTE}")


def _load_module(path: Path, name: str, extra_sys_path: Path | None = None):
    added = False
    if extra_sys_path is not None and str(extra_sys_path) not in sys.path:
        sys.path.insert(0, str(extra_sys_path))
        added = True
    try:
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.modules.pop(name, None)
        if added:
            sys.path.remove(str(extra_sys_path))


def test_no_forbidden_paths_remain():
    pattern = re.compile("|".join(FORBIDDEN_PATTERNS))
    offenders = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        if any(part in EXCLUDED_DIR_NAMES for part in path.parts):
            continue
        # mating_index/datasets/holdout_* is gitignored, regenerated by train.py,
        # and stamps the absolute path of whatever machine last ran it (Ultralytics
        # args.yaml / data.yaml) - not tracked source, so not a leak.
        if any(part.startswith("holdout_") for part in path.parts):
            continue
        if path == Path(__file__):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if pattern.search(text):
            offenders.append(str(path.relative_to(REPO_ROOT)))
    assert not offenders, f"machine-specific paths found in: {offenders}"


def test_mobility_index_bundled_artifacts_exist():
    """models/ is tracked in git, so these must always resolve.

    occlusion_weights is deliberately excluded: the occlusion classifier is not bundled
    (opt-in only, off by default via ``use_occlusion=False``).
    """
    mobility_dir = REPO_ROOT / "mobility_index"
    module = _load_module(mobility_dir / "config.py", "mobility_config_under_test")
    cfg = module.CONFIG
    assert not cfg.use_occlusion, "use_occlusion should default to False (no bundled model)"
    for attr in ("seg_weights", "marker_model", "marker_scaler"):
        p = getattr(cfg, attr)
        assert p.exists(), f"MobilityConfig.{attr} does not exist: {p}"


def test_mobility_index_mendeley_dataset_paths_exist():
    mobility_dir = REPO_ROOT / "mobility_index"
    module = _load_module(mobility_dir / "config.py", "mobility_config_under_test")
    cfg = module.CONFIG
    _skip_if_dataset_missing(cfg.experiment_root)
    assert cfg.reid_gallery_dir.exists(), cfg.reid_gallery_dir


def test_mating_index_roi_jsons_exist():
    """datasets/additional/mating_phenotyping_rois/ ships with the Mendeley archive,
    not in git - skip (don't fail) if it hasn't been downloaded/extracted yet."""
    mating_dir = REPO_ROOT / "mating_index"
    module = _load_module(mating_dir / "mating" / "config.py", "mating_config_under_test")
    cfg = module.MatingConfig()
    _skip_if_dataset_missing(cfg.roi_json(cfg.series[0]))
    for series in cfg.series:
        p = cfg.roi_json(series)
        assert p.exists(), f"roi_json({series!r}) does not exist: {p}"


def test_reid_benchmark_default_dataset_root_exists():
    reid_dir = REPO_ROOT / "reid_benchmark"
    try:
        module = _load_module(reid_dir / "train.py", "reid_train_under_test", extra_sys_path=reid_dir)
    except ImportError as exc:
        pytest.skip(f"reid_benchmark's full dependency stack is not installed: {exc}")
    _skip_if_dataset_missing(Path(module.DEFAULT_DATASET_ROOT))
